IF (WIN32)
    set(OCL_LIBRARIES ${PROJECT_SOURCE_DIR}/Dependencies/OpenCL/Lib/OpenCL.lib)
ELSE (WIN32)
    FIND_LIBRARY(OCL_LIBRARIES OpenCL ENV LD_LIBRARY_PATH)
ENDIF (WIN32)

list(APPEND OCL_INCLUDE_DIR "${PROJECT_SOURCE_DIR}/Dependencies/OpenCL/Include")

SET(OCL_FOUND "NO")
IF(OCL_LIBRARIES)
    SET(OCL_FOUND "YES")
    message("OCL found\n")
ENDIF(OCL_LIBRARIES)

MARK_AS_ADVANCED(
  OCL_INCLUDE_DIR
)